### ISSUE TITLE
Notification does not show in track bar when app is open.

### ISSUE THREAD

**Issue by Aniket-ajency** [taivo/parse-push-plugin#21]
I am using parse push notification with ionic framework the notification are working fine when app is in coldstart but when app is in foreground then I am not able to see notification in my track bar but my recivePN is getting called.
And one more thing when my app is destroyed then also I am not able to get any push notification.

**Comment by wathmal** [comment]
hi, i am facing with same issues. any luck in this ??

**Comment by taivo** [comment]
Notification not appearing in tray when app is running. That behavior is intentional. I figure when the app is on it should handle notification and not spam the tray. I've been meaning to add a configurable option to allow tray notification even when the app is on, but I haven't found the time. Perhaps you guys can help.

The code to create tray notification is in ParsePushPluginReceiver.java, function `onPushReceive`.
