### ISSUE TITLE
Bug: length not set of undefined

### ISSUE THREAD

**Issue by dirkpostma** [taivo/parse-push-plugin#23]
In cordova 5.4.1 on android 5.0, I get an error in the console:

    length not set of undefined

This happens when cordova.exec( ... ) is called with only four parameters, as done in parse-push-plugin.js on lines 37, 46, 50 and 54.

Adding emtpy array as fifth parameter solves the issue.
e.g.:

    cordova.exec(successCb, errorCb, serviceName, 'getInstallationId', []);

I'll create a PR later.

**Comment by taivo** [comment]
Urgh, I took those empty arrays out a couple days ago because cordova-ios's version of exec automatically checked and assign an empty array if that 4th parameter isn't there. 

I thought that would make the code look cleaner...that's what I get for messing with code that's been working just fine. Thank you for spotting it.
