### ISSUE TITLE
initialise parse in an app 

### ISSUE THREAD

**Issue by sharmahemu1994** [taivo/parse-push-plugin#32]
how to initialize the parse into an app.

**Comment by taivo** [comment]
Depends on Android or iOS. Both are in the README docs of this repo

**Comment by sharmahemu1994** [comment]
Hello, thanks for reply. :-)
I want to initialize parse in Ionic/cordova.

**Comment by taivo** [comment]
Yes, the init code in the docs is meant for initializing parse in ionic/cordova. 

In case you mean initializing parse in the javascript side of cordova, there isn't a special way to do that. Just init parse in javascript the way you would even if you don't use this plugin. The init methods shown in the docs will initialize the native parse engine for your app. In other words, there should be 2 parse initializations: one in js using the js key, and one as documented using the client key.

In case you mean triggering native initialization from javascript: you don't want to do that. The cordova webview (and javascript bridge) becomes ready too late in the init chain to handle notifications that arrive in the cold start scenario. In other words, if a notification arrives when your app is not running, the app will start and tell this plugin to handle the notification and crash because Parse is not initialized. All this happens before javascript has a chance to do any init.
