### ISSUE TITLE
What is the custom subevents?

### ISSUE THREAD

**Issue by zhouhao27** [taivo/parse-push-plugin#35]
I saw your readme and found something call "custom subevents". Can you explain what it is? Thanks

**Comment by taivo** [comment]
Custom subevent is just a way for you to divide up the `receivePN` event into different categories like chat or system messages. This way you can write separate handlers for distinctly different subsystems within your app. Here are the examples I gave in the docs

```javascript
//
//you can also listen to your own custom subevents
//
ParsePushPlugin.on('receivePN:chat', chatEventHandler);
ParsePushPlugin.on('receivePN:serverMaintenance', serverMaintenanceHandler);
```

**Comment by zhouhao27** [comment]
But how to emit such sub event in Dashboard?

**Comment by taivo** [comment]
Ah, in the json payload of of your push notif, add a field called "event" and set it to something like "chat". This info used to be mentioned in the docs but I must have removed it by mistake.

BTW, with Parse winding down their service, why are you still using this plugin?

**Comment by campers** [comment]
I'm migrating my app which uses this plugin to the open source server atm. Would it still be usable or just use the standard push notification plugin?

**Comment by taivo** [comment]
I don't know the exact answer because I have not tried this yet. However, I suspect it is possible with only some minor mods because most of this plugin is client-side management of a push notification after it has been received. It's mostly the configuration that is bound to the soon-to-depart Parse.com

I will try to allot sometime to migrate this plugin in a couple of weeks. If you have more info about this, please share. Thanks.
