### ISSUE TITLE
Why don't initialize parse and Push registration inside Javscript code?

### ISSUE THREAD

**Issue by zhouhao27** [taivo/parse-push-plugin#36]
As a cordova plugin, asking user to modify/add code in ios/android project is not very convenient. Is it possible to create a function to initialize parse and register push like some of other plugin does? Thanks.

**Comment by taivo** [comment]
Parse initialization has to be done on the native side for the cold start case to work properly. This is because push notification handling happens before the javascript bridge becomes ready. 

I personally prefer for things to be completely handled by calling a js function too, but afaik this is the initialization flow of Android and iOS.
