### ISSUE TITLE
Latest version crashes on Android

### ISSUE THREAD

**Issue by ladmerc** [taivo/parse-push-plugin#58]
I installed the current commit 239951caaf82f99ab378dddae16006af87f4e7d9 and it's been crashing on Android. I've uninstalled the plugin on three occasions and app runs well on device and emulator. Reinstall the plugin, and it crashes:

Logcat.txt says something about skipping too many frames (about 50-60)

**Comment by vesters** [comment]
+1

**Comment by taivo** [comment]
@vesters are you getting the same error about skipping too many frames?

Right now I'm not entirely sure how that can possibly be related to this notification plugin

**Comment by taivo** [comment]
Also, can you guys check the `application` tag in your android manifest? Make sure the `android:name` attribute says `github.taivo.parsepushplugin.ParsePushApplication`

Please see my last post on issue #55 for more info. And let me know how things go. I'll do my best to help.

**Comment by vesters** [comment]
@taivo I don't actually know if that's the error I'm getting. I don't know how to get the logs, because the crash happens right after open.

I just narrowed the crash down to this plugin, and it was working on my last release a couple of months ago.

I have successfully created a fresh ionic install with this plugin, that doesn't crash though.

**Comment by quilligana** [comment]
I can confirm the same issue and that uninstalling and re-installing the plugin fixes the issue as per @taivo post on #55 (i.e. `android:name` in `application` tag of android manifest). Not sure why the issue happened in the first place though.

**Comment by taivo** [comment]
@vesters, @ladmerc, have you guys had a chance to check the manifest?

To view log, just turn on adb logcat on the console while your phone is connected to computer via usb. 

There is something weird happening with the Cordova hook that sets android:name. I'm wondering if another plugin clears that entry. If possible, can you list your plugins here? I can do some inspection when I get a chance. 

Thanks

**Comment by vesters** [comment]
I haven't looked at it further, since a fresh Ionic install took care of
the problem for me - obviously not something I'd like to do often though :)

Here are my list of plugins:

cordova-fabric-plugin 1.0.8 "cordova-fabric-plugin"
cordova-plugin-compat 1.0.0 "Compat"
cordova-plugin-console 1.0.3 "Console"
cordova-plugin-device 1.1.2 "Device"
cordova-plugin-facebook4 1.7.2 "Facebook Connect"
cordova-plugin-firebase 0.1.10 "Google Firebase Plugin"
cordova-plugin-geolocation 2.2.0 "Geolocation"
cordova-plugin-splashscreen 3.2.2 "Splashscreen"
cordova-plugin-statusbar 2.1.3 "StatusBar"
cordova-plugin-whitelist 1.2.2 "Whitelist"
ionic-plugin-keyboard 2.2.1 "Keyboard"
parse-push-plugin 1.0.5 "ParsePushPlugin"
phonegap-plugin-push 1.8.1 "PushPlugin"

**Comment by taivo** [comment]
@vesters, thank you for your list.

**Comment by vesters** [comment]
@taivo Thank you for working on the plugin. Would be lost without it!

**Comment by ladmerc** [comment]
Didn't check the Manifest as I had to use another plugin instead.

Cheers man!

**Comment by quilligana** [comment]
I've noticed that if I `cordova platform rm android` and then `cordova platform add android` the `android:name` tag in `application` of `config.xml` is missing. Uninstalling the plugin and reinstalling then solves this:

```
cordova plugin rm parse-push-plugin
cordova plugin add https://github.com/taivo/parse-push-plugin
```

and hence the crashing issues.

**Comment by taivo** [comment]
@quilligana, that observation makes a lot of sense given some of the unexplained disappearance of android:name in the manifest. 

That attribute is filled via a cordova hook during the plugin installation phase. Perhaps I can move that work to the after_prepare phase instead. 

Thanks for sharing your insight.
