### ISSUE TITLE
[IONIC-ANDROID] REGISTRATION NOT INSERT IN INSTALLATION TABLE ON DB

### ISSUE THREAD

**Issue by esoni** [taivo/parse-push-plugin#70]
Hi all,
i've tried to setup this plugin as described in your main page.. i've configured config.xml and in the end i've written the following code
`$ionicPlatform.ready(function(){
   if(window.ParsePushPlugin){
      ParsePushPlugin.getInstallationId(function(id) {
         // note that the javascript client has its own installation id,
         // which is different from the device installation id.
          alert("device installationId: " + id);
      }, function(e) {
          alert('error');
      });

      ParsePushPlugin.getSubscriptions(function(subscriptions) {
          alert(subscriptions);
      }, function(e) {
          alert('error');
      });

      ParsePushPlugin.subscribe('SampleChannel', function(msg) {
          alert('OK');
      }, function(e) {
          alert('error');
      });

   }
});`

The result is that the alert correctly show the installation id but not insert in the db the related installation record in table Installations..
Did you know a possible root cause ?
Thanks
Dario

**Comment by esoni** [comment]
Hi,
i give you major details .. in 'platforms/android/AndroidManifest.xml have the application tag  set
to 
android:name="github.taivo.parsepushplugin.ParsePushApplication"
But i dont have a folder github/taivo/parsepushplugin/ in my workspace .. is this the issue ?

**Comment by taivo** [comment]
Hi @esoni , the `github/taivo/parsepushplugin` dir should be under `platforms/android/src`.

That said, in the recent past, when there is a strange error like this, other users have reported that an older android platform was the issue. Can you try removing your android platform, readd it, then readd the plugin?

Let me know.

**Comment by esoni** [comment]
all it solved i ve reinstalled the plugin.
Thanks..
I need another info: this lib is compatible with IOS ?

Thanks
Dario

**Comment by taivo** [comment]
Should work with iOS as stated in the readme. Only uwp still a work in progress.

**Comment by rooswelt** [comment]
Same problem here.
Works fine on iOS.
No installation row on android.
Tried to reboot device, remove and re-add platform, remove and re-add plugin. No luck

No error in both client or server.

Any advice?

**Comment by temitope** [comment]
Same issue on Android. No installation row being created. I am also getting a null value for the installation object id when I try to retrieve it with 
ParsePushPlugin get.InstallationObjectId 

I am noticing this warning being sent out, but not sure if it is related. looking into maybe initializing parse js sdk with a clientid
_"Ignoring header X-Parse-Client-Key because its value was null"_

**Comment by temitope** [comment]
SUCCESS! It turned out that I was missing the trailing slash "/" on my parserServerURL variable...wow. that was it. I noticed it by looking into ParsePushApplication.java under the plugin project in Android studio. There was a comment in there (great job coder) stating that the trailing slash was important (this is currently on line 70). I just added the slash and voila, the installation id came through on my next send.  

 This is one of the hallmarks of programming in my life. Hours and hours of time over something as "small" as a single character, and i love it. Well I hope this works for someone else too.

Not sure if the solution is to add this to trouble shooting section of documentation or maybe do a check programmatically to add the slash. Thanks to everyone who worked on this project. #52
