### ISSUE TITLE
Ionic2 suport

### ISSUE THREAD

**Issue by cleever** [taivo/parse-push-plugin#82]
Does anybody use this plugin with typescript and Ionic2?

**Comment by cleever** [comment]
Works well with Ionic2.

**Comment by alirva** [comment]
Hi @cleever I'm, but I'm having problems because it never creates the installation row in my database,  I've already installed the plugin in my app and imported well, also ParsePushPlugin.getInstallationId is working fine, it gets me an id, but when I check in database the "Installation" class continues empty, do you have any idea what it could be?  Thanks in advance

**Comment by cleever** [comment]
Hi @Marcelinne,

See my answer here: https://github.com/taivo/parse-push-plugin/issues/107
